
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: AcChat_development

test:
  <<: *default
  database: AcChat_test

production:
  <<: *default
  database: postgres
  username: popac
  password: popac
