
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: AcChat_development

test:
  <<: *default
  database: AcChat_test

production:
  <<: *default
  database: d4vs4sopc51tpj
  username: spnnbadltyxagd
  password: i81pd8lavip-b6t5CbI4nwD2Bc
