# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36892284858d76335bb3c87adeff17f51a94a84cb140f0fda983b570e99508070bdfb7d5a3a72d318693721bf532b16a13df0fea6ea293c494789aaa2cac4a7d

test:
  secret_key_base: 110f8a12d9b7870e8ea6d3825267793ccab09553f0d31d6160bcf6a8d0d3ced3995582e75d283d05f50e701a1ab75e72937db8932dbfec3a402400c8ce2fb0c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
